CFLAGS = /I"C:\Program Files\Microsoft SDKs\Windows\v7.0\Include" /c
LFLAGS = /libpath:"C:\Program Files\Microsoft SDKs\Windows\v7.0\Lib" /subsystem:windows

TARGET = Starships.scr

SOURCES = \
		*.cpp

all: $(TARGET)

clean:
		erase $(TARGET)
		erase *.obj
		erase *.res
		erase *.manifest

$(TARGET):$(SOURCES)
		cl $(CFLAGS) $**
		rc resources.rc
		cvtres /MACHINE:X86 resources.res
		link $(LFLAGS) /out:$(TARGET) screensaver.obj ship.obj resources.obj
		mt -manifest $(TARGET).manifest -outputresource:$(TARGET)
